In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
a=["a","b","a","b",'c','a','c','c','b','b','b' ,'a','b','c']
a=pd.DataFrame(a)
a

0
0   a
1   b
2   a
3   b
4   c
5   a
6   c
7   c
8   b
9   b
10  b
11  a
12  b
13  c

In [6]:
le=LabelEncoder()
a_le=le.fit_transform(a[0])
a_le

array([0, 1, 0, 1, 2, 0, 2, 2, 1, 1, 1, 0, 1, 2])

In [17]:
oe=OneHotEncoder()
a_oe=oe.fit_transform(a).toarray()
a_oe


array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
from mlxtend.preprocessing import TransactionEncoder

dataset = [['Apple', 'Beer', 'Rice', 'Chicken'],
           ['Apple', 'Beer', 'Rice'],
           ['Apple', 'Beer'],
           ['Apple', 'Bananas'],
           ['Milk', 'Beer', 'Rice', 'Chicken'],
           ['Milk', 'Beer', 'Rice'],
           ['Milk', 'Beer'],
           ['Apple', 'Bananas']]

In [19]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
te_ary

array([[ True, False,  True,  True, False,  True],
       [ True, False,  True, False, False,  True],
       [ True, False,  True, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True],
       [False, False,  True, False,  True, False],
       [ True,  True, False, False, False, False]])

In [20]:
te_ary.astype("int")

array([[1, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 0, 0]])

In [21]:
te.columns_

['Apple', 'Bananas', 'Beer', 'Chicken', 'Milk', 'Rice']

In [22]:
import pandas as pd

pd.DataFrame(te_ary, columns=te.columns_)

Apple  Bananas   Beer  Chicken   Milk   Rice
0   True    False   True     True  False   True
1   True    False   True    False  False   True
2   True    False   True    False  False  False
3   True     True  False    False  False  False
4  False    False   True     True   True   True
5  False    False   True    False   True   True
6  False    False   True    False   True  False
7   True     True  False    False  False  False