In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,r2_score,accuracy_score
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.datasets import fetch_20newsgroups

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn .decomposition import PCA
from sklearn.pipeline  import Pipeline

In [4]:
data=fetch_20newsgroups()

In [5]:
data.target_names,data.target

(['alt.atheism',
  'comp.graphics',
  'comp.os.ms-windows.misc',
  'comp.sys.ibm.pc.hardware',
  'comp.sys.mac.hardware',
  'comp.windows.x',
  'misc.forsale',
  'rec.autos',
  'rec.motorcycles',
  'rec.sport.baseball',
  'rec.sport.hockey',
  'sci.crypt',
  'sci.electronics',
  'sci.med',
  'sci.space',
  'soc.religion.christian',
  'talk.politics.guns',
  'talk.politics.mideast',
  'talk.politics.misc',
  'talk.religion.misc'],
 array([7, 4, 4, ..., 3, 1, 8]))

In [6]:
x_train,x_test,y_train,y_test=train_test_split(data.data,data.target,train_size=0.8)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB,GaussianNB,BernoulliNB
from sklearn.pipeline import make_pipeline

In [8]:
nb=make_pipeline(TfidfVectorizer(),MultinomialNB())
model1=nb.fit(x_train,y_train)

In [9]:
accuracy_score(y_test,model1.predict(x_test))

0.8510826336721167

In [10]:
confusion_matrix(y_test,model1.predict(x_test)).trace(),(np.sum(confusion_matrix(y_test,model1.predict(x_test))))

(1926, 2263)

In [11]:
def predict_category(s,model=model1):
    pred=model.predict([s])
    return data.target_names[pred[0]]
a=input("enter string: ")
predict_category(a)

enter string: furu


'rec.motorcycles'

In [12]:
model1.predict(["im the president of INDIA"])[0]

18

In [13]:
from sklearn.metrics import classification_report,precision_score,recall_score,multilabel_confusion_matrix


In [14]:
classification_report(y_test,model1.predict(x_test))

'              precision    recall  f1-score   support\n\n           0       0.87      0.67      0.76       114\n           1       0.84      0.74      0.79       109\n           2       0.88      0.80      0.84       117\n           3       0.83      0.74      0.78       141\n           4       0.83      0.88      0.85       104\n           5       0.92      0.89      0.91       109\n           6       0.92      0.74      0.82       104\n           7       0.83      0.92      0.87       110\n           8       0.89      0.95      0.92       105\n           9       0.90      0.95      0.92       117\n          10       0.94      0.98      0.96       132\n          11       0.79      0.99      0.88       125\n          12       0.92      0.78      0.84       122\n          13       0.98      0.90      0.94       118\n          14       0.88      0.96      0.92       111\n          15       0.52      0.98      0.68       118\n          16       0.84      0.98      0.90       115\n       

In [15]:
precision_score(y_test,model1.predict(x_test),average="macro")

0.8773924110796265

In [16]:
recall_score(y_test,model1.predict(x_test),average="macro")

0.8349579460876685

In [17]:
from sklearn.datasets import load_digits
data=load_digits()
x_train2,x_test2,y_train2,y_test2=train_test_split(data.data,data.target,train_size=0.8)
nb=make_pipeline(MultinomialNB())
model2=nb.fit(x_train2,y_train2)


In [18]:
accuracy_score(y_test2,model2.predict(x_test2))

0.8861111111111111

# gaussion model

In [19]:
gb=Pipeline([("scaler",StandardScaler()),("p1",PCA()),("gb",GaussianNB())])
model3=gb.fit(x_train2,y_train2)
accuracy_score(y_test2,model3.predict(x_test2))

0.9027777777777778

In [20]:
confusion_matrix(y_test2,model3.predict(x_test2))

array([[30,  0,  0,  0,  0,  1,  1,  0,  0,  0],
       [ 0, 37,  0,  0,  1,  0,  0,  0,  1,  0],
       [ 0,  1, 28,  1,  1,  0,  0,  1,  3,  0],
       [ 0,  0,  1, 26,  0,  0,  0,  1,  2,  3],
       [ 0,  3,  0,  0, 29,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  1,  0, 40,  0,  0,  0,  0],
       [ 0,  1,  1,  0,  0,  0, 33,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 38,  0,  2],
       [ 0,  1,  1,  0,  0,  0,  0,  0, 26,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2, 38]], dtype=int64)

In [21]:
classification_report(y_test2,model3.predict(x_test2))

'              precision    recall  f1-score   support\n\n           0       1.00      0.94      0.97        32\n           1       0.86      0.95      0.90        39\n           2       0.90      0.80      0.85        35\n           3       0.93      0.79      0.85        33\n           4       0.94      0.88      0.91        33\n           5       0.98      0.98      0.98        41\n           6       0.97      0.89      0.93        37\n           7       0.95      0.95      0.95        40\n           8       0.70      0.87      0.78        30\n           9       0.84      0.95      0.89        40\n\n    accuracy                           0.90       360\n   macro avg       0.91      0.90      0.90       360\nweighted avg       0.91      0.90      0.90       360\n'

In [22]:
precision_score(y_test2,model3.predict(x_test2),average='weighted')

0.9095985866950667

# Bernoulli model

In [23]:
bb=Pipeline([("scaler",StandardScaler()),("p1",PCA()),("bb",BernoulliNB())])
model4=bb.fit(x_train2,y_train2)
accuracy_score(y_test2,model4.predict(x_test2))

0.8

In [24]:
confusion_matrix(y_test2,model4.predict(x_test2))

array([[26,  1,  0,  0,  2,  2,  1,  0,  0,  0],
       [ 0, 31,  3,  0,  1,  1,  0,  0,  3,  0],
       [ 0,  5, 25,  3,  0,  0,  0,  0,  2,  0],
       [ 0,  1,  0, 24,  0,  0,  0,  0,  4,  4],
       [ 0,  3,  0,  1, 28,  0,  0,  0,  0,  1],
       [ 0,  0,  1,  1,  0, 38,  1,  0,  0,  0],
       [ 0,  4,  0,  0,  1,  0, 31,  0,  1,  0],
       [ 2,  0,  0,  2,  1,  1,  0, 31,  2,  1],
       [ 0,  4,  1,  1,  0,  0,  0,  1, 22,  1],
       [ 0,  1,  0,  5,  0,  0,  0,  0,  2, 32]], dtype=int64)

In [25]:
precision_score(y_test2,model4.predict(x_test2),average='weighted')

0.8172861605361605