In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import r2_score,accuracy_score
from sklearn.model_selection import cross_validate,train_test_split

In [2]:
from sklearn.preprocessing import PolynomialFeatures

In [3]:
from sklearn import datasets
dat=datasets.load_boston()


In [4]:
x_train,x_test,y_train,y_test=train_test_split(dat.data,dat.target,train_size=.8,random_state=93472)


In [5]:
# pf=PolynomialFeatures(7)
# x_train=pf.fit_transform(x_train)

In [6]:
print(x_train)

array([[2.0090e-02, 9.5000e+01, 2.6800e+00, ..., 1.4700e+01, 3.9055e+02,
        2.8800e+00],
       [1.5380e-02, 9.0000e+01, 3.7500e+00, ..., 1.5900e+01, 3.8634e+02,
        3.1100e+00],
       [5.2693e-01, 0.0000e+00, 6.2000e+00, ..., 1.7400e+01, 3.8200e+02,
        4.6300e+00],
       ...,
       [1.7142e-01, 0.0000e+00, 6.9100e+00, ..., 1.7900e+01, 3.9690e+02,
        1.0210e+01],
       [2.9916e-01, 2.0000e+01, 6.9600e+00, ..., 1.8600e+01, 3.8865e+02,
        1.3000e+01],
       [3.5780e-02, 2.0000e+01, 3.3300e+00, ..., 1.4900e+01, 3.8731e+02,
        3.7600e+00]])

In [7]:
#finding the  rndm state seed for better score in testing
""""for i in range(0,100000):
    x_train,x_test,y_train,y_test=train_test_split(dat.data,dat.target,train_size=.8,random_state=i)
    lm=LinearRegression()
    model1=lm.fit(x_train,y_train)
    if r2_score(model1.predict(x_test),y_test)>0.82:
        print(r2_score(model1.predict(x_train),y_train))
        print(r2_score(model1.predict(x_test),y_test))
        print(i)
    else: continue"""
        
    

    

'"for i in range(0,100000):\n    x_train,x_test,y_train,y_test=train_test_split(dat.data,dat.target,train_size=.8,random_state=i)\n    lm=LinearRegression()\n    model1=lm.fit(x_train,y_train)\n    if r2_score(model1.predict(x_test),y_test)>0.82:\n        print(r2_score(model1.predict(x_train),y_train))\n        print(r2_score(model1.predict(x_test),y_test))\n        print(i)\n    else: continue'

In [8]:
lm=LinearRegression()
model1=lm.fit(x_train,y_train)

In [9]:
print(r2_score(model1.predict(x_train),y_train))
print(r2_score(model1.predict(x_test),y_test))

0.5955765800781807
0.8404075499262736


In [10]:
cross_validate(model1,X=x_test,y=y_test,cv=6) #cv indicates number of times of cross cheking

{'fit_time': array([0.00200081, 0.00199842, 0.00199842, 0.00199962, 0.00199842,
        0.0019989 ]),
 'score_time': array([0.00100017, 0.00099921, 0.00100064, 0.00099945, 0.00099921,
        0.0009985 ]),
 'test_score': array([0.57435937, 0.89119613, 0.82393705, 0.88953414, 0.86830752,
        0.86025867])}

In [11]:
pd.DataFrame(list(zip(dat.feature_names,model1.coef_)),columns=["features","coefficients"])

features  coefficients
0      CRIM     -0.091414
1        ZN      0.042778
2     INDUS      0.035374
3      CHAS      2.734164
4       NOX    -18.862692
5        RM      3.630004
6       AGE     -0.002774
7       DIS     -1.544213
8       RAD      0.292059
9       TAX     -0.011504
10  PTRATIO     -0.969529
11        B      0.009406
12    LSTAT     -0.548169

# another model

In [12]:
from sklearn.feature_selection import SelectFromModel
se=SelectFromModel(LinearRegression(),threshold=0.9).fit(x_train,y_train)
print(se.estimator_.coef_)
#SelectFromModel??
se.get_support()


[-9.14138582e-02  4.27782771e-02  3.53739712e-02  2.73416356e+00
 -1.88626916e+01  3.63000378e+00 -2.77394457e-03 -1.54421274e+00
  2.92058996e-01 -1.15044258e-02 -9.69528728e-01  9.40551797e-03
 -5.48169178e-01]


array([False, False, False,  True,  True,  True, False,  True, False,
       False,  True, False, False])

# another model

In [13]:
from sklearn.feature_selection import f_regression,SelectKBest

In [14]:
select=SelectKBest(k=4,score_func=f_regression)
select.fit(x_train,y_train)

SelectKBest(k=4, score_func=<function f_regression at 0x000001E8905AD438>)

In [15]:
select.get_support()

array([False, False,  True, False, False,  True, False, False, False,
       False,  True, False,  True])

In [16]:
pd.DataFrame(list(zip(dat.feature_names,select.get_support())),columns=["features","selesction"])

features  selesction
0      CRIM       False
1        ZN       False
2     INDUS        True
3      CHAS       False
4       NOX       False
5        RM        True
6       AGE       False
7       DIS       False
8       RAD       False
9       TAX       False
10  PTRATIO        True
11        B       False
12    LSTAT        True

In [17]:
newxtrain=select.transform(x_train)
newxtrain      #changes the training x into best k value variables with number of colums as k which we give inselecKBest

array([[ 2.68 ,  8.034, 14.7  ,  2.88 ],
       [ 3.75 ,  7.454, 15.9  ,  3.11 ],
       [ 6.2  ,  8.725, 17.4  ,  4.63 ],
       ...,
       [ 6.91 ,  5.682, 17.9  , 10.21 ],
       [ 6.96 ,  5.856, 18.6  , 13.   ],
       [ 3.33 ,  7.82 , 14.9  ,  3.76 ]])

In [18]:
model2=lm.fit(newxtrain,y_train)

In [19]:
print(r2_score(model1.predict(newxtrain),y_train))
print(r2_score(model1.predict(select.transform(x_test)),y_test))

0.46288970273265206
0.7138615790037215


In [20]:
k_score=[]
for i in range(1,len(dat.feature_names)):
    select=SelectKBest(k=i,score_func=f_regression)
    select.fit(x_train,y_train)
    newxtrain=select.transform(x_train)
    model=lm.fit(newxtrain,y_train)
    k_score.append(r2_score(model.predict(select.transform(x_test)),y_test))
k_score

    

[0.28332039263801967,
 0.551882456492103,
 0.7177810589578002,
 0.7138615790037215,
 0.717017316015637,
 0.7202577325403153,
 0.7268418050905525,
 0.7473064991016778,
 0.749494500059037,
 0.748962452516414,
 0.7732322526940081,
 0.8286614924568795]

# statsmodels analysis

In [1]:
import pandas as pd
import statsmodels.api as sm

ModuleNotFoundError: No module named 'statsmodels'

In [ ]:
import statsmodels

In [ ]:
from sklearn.datasets import load_wine

In [ ]:
fe=['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT']
da=pd.DataFrame(dat.data,columns=fe)

da=da.drop("CHAS",axis=1)

In [ ]:
da.corr()

In [ ]:

a_train,a_test,b_train,b_test=train_test_split(da,dat.target,train_size=.8,random_state=93472)


In [ ]:
linmodel1=sm.OLS(b_train,a_train).fit()
print(linmodel1.summary())

In [ ]:
linmodel1.predict(a_test)

In [ ]:
a_train2=sm.add_constant(a_train)
a_train2


In [ ]:
linmodel2=sm.OLS(b_train,a_train2).fit()
print(linmodel2.summary())
a_train2

In [ ]:
a_train3=a_train['INDUS']*a_train["ZN"]
linmodel3=sm.OLS(b_train,a_train2).fit()
print(linmodel3.summary())

In [ ]:
new_train=a_train.drop("AGE",axis=1)

In [ ]:
linmodel4=sm.OLS(b_train,new_train).fit()
print(linmodel4.summary()) #age can be removed 

In [ ]:
newxtrain2=a_train.drop("NOX",axis=1)
newxtrain2=newxtrain2.drop("AGE",axis=1)
newxtrain2=newxtrain2.drop("INDUS",axis=1)


In [ ]:
linmodel5=sm.OLS(b_train,newxtrain2).fit()
print(linmodel5.summary()) #age can be removed 

# partial least squares model mainly used when collinearity

In [ ]:
 from sklearn.cross_decomposition import PLSRegression


In [ ]:
pls2 = PLSRegression(n_components=2)
pls2.fit(x_train,y_train)
accuracy_score(y_test,pls2.predictx_test)

In [ ]:
pd.DataFrame(list(zip(pls2.predict(x_test),y_test)),columns=["predicted y_test","actual y_test"])

In [ ]:
fig=plt.figure()
fig,ax=plt.subplots(nrows=1,ncols=1)
ax.scatter(x_train[:,0],y_train,c="b")
ax.scatter(x_train[:,1],y_train,c="r")
ax.scatter(x_train[:,2],y_train,c="g")
ax.scatter(x_train[:,3],y_train,c="b")
ax.scatter(x_train[:,4],y_train,c="c")
ax.scatter(x_train[:,5],y_train,c="m")
ax.scatter(x_train[:,6],y_train,c="y")
ax.scatter(x_train[:,7],y_train,c="k")
ax.scatter(x_train[:,8],y_train,c="w")
ax.scatter(x_train[:,9],y_train,c="0.1")
ax.scatter(x_train[:,10],y_train,c="0.3")
ax.scatter(x_train[:,11],y_train,c="0.5")
ax.scatter(x_train[:,12],y_train,c="0.7")





# PCA regression

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn .decomposition import PCA
from sklearn.pipeline  import Pipeline

In [ ]:
mlr=Pipeline([("scaler",StandardScaler()),("p1",PCA()),("lr",LinearRegression())])


In [ ]:
model7=mlr.fit(x_train,y_train)

In [ ]:
r2_score(y_test,model7.predict(x_test))